[package]
name = "f4"
version = "0.2.4"
edition = "2024"

[dependencies]
rand = "0.9.0"
is_prime = "2.0.9"
rayon = "1.10.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[profile.profiling]
inherits = "release"
debug = true
